version: "3.7"
services:
  redis:
    image: telkomindonesia/alpine:redis-5.0
    environment:
      REDIS_PASSWORD: 1231easdc
    restart: always
    ports:
      - 6379:6379
    volumes:
       - ./redis:/var/lib/redis/data
  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password1
      MYSQL_USER: user_tiket
      MYSQL_PASSWORD: Tiket@12ed
      MYSQL_DATABASE: tiket
    ports:
      - 3309:3306
  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: leomessi
    ports:
      - 3307:3306
    volumes:
      - ./mariadb:/var/lib/mysql
  web:
    image: telkomindonesia/debian-buster:php-7.4-apm-apache-novol
    container_name: web
    volumes:
      - ./web:/var/www/html
    environment:
      DB_HOST: mysql
      DB_USER: user_tiket
      DB_PASS: Tiket@12ed
      DATABASE: tiket
      RECAPTCHA_SITE_KEY: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
      RECAPTCHA_SECRET_KEY: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
      SALT: e545d2da-97eb-4f1a-a641-5a9ec4d19861
      HOST: http://localhost:8080/
    ports:
      - 8080:8080