version: "3.7"
services:
  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: leomessi
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql

  web:
    image: telkomindonesia/debian-buster:php-7.4-apm-apache-novol
    container_name: web
    volumes:
      - ./web:/var/www/html
    environment:
      DB_HOST: mariadb
      DB_USER: root
      DB_PASS: leomessi
      DATABASE: db_karcis
      HOST: http://localhost:8080/
    ports:
      - 8080:8080

volumes:
  mariadb_data: