version: "3.7"
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password1
      MYSQL_USER: user_tiket
      MYSQL_PASSWORD: Tiket@12ed
    ports:
      - 3309:3306
  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: leomessi
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
  web:
    image: telkomindonesia/debian-buster:php-7.4-apm-apache-novol
    container_name: web
    volumes:
      - ./web:/var/www/html
    environment:
      DB_HOST: mysql
      DB_USER: user_tiket
      DB_PASS: Tiket@12ed
      DATABASE: tiket
      HOST: http://localhost:8080/
    ports:
      - 8080:8080